import 'package:dotdart/src/parsers/svg/svg_mini_xml.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  group('XParser', () {
    test('when XML has a declaration and leading comment, it should return the SVG root', () {
      final root = XParser.parse(
        '''
<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by a vector editor. -->
<svg viewBox="0 0 24 24"/>
'''
            .trimLeft(),
      );

      expect(root.tag, 'svg');
    });

    test('when XML starts with a byte order mark and declaration, it should return the SVG root', () {
      final root = XParser.parse('\uFEFF<?xml version="1.0"?><svg viewBox="0 0 24 24"/>');

      expect(root.tag, 'svg');
    });

    test('when an XML declaration is unterminated, it should throw a FormatException', () {
      expect(
        () => XParser.parse('<?xml version="1.0"<svg viewBox="0 0 24 24"/>'),
        throwsA(isA<FormatException>()),
      );
    });

    test('when an XML declaration omits its version, it should throw a FormatException', () {
      expect(
        () => XParser.parse('<?xml encoding="utf-8"?><svg viewBox="0 0 24 24"/>'),
        throwsA(isA<FormatException>()),
      );
    });

    test('when an XML declaration has an unknown field, it should throw a FormatException', () {
      expect(
        () => XParser.parse('<?xml version="1.0" source="editor"?><svg viewBox="0 0 24 24"/>'),
        throwsA(isA<FormatException>()),
      );
    });

    test('when an XML declaration has mismatched quotes, it should throw a FormatException', () {
      expect(
        () => XParser.parse('<?xml version="1.0\'?><svg viewBox="0 0 24 24"/>'),
        throwsA(isA<FormatException>()),
      );
    });
  });
}
